name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: Gemfile
            ruby: 3.2
          - gemfile: Gemfile
            ruby: 3.1
          - gemfile: gemfiles/gslr.gemfile
            ruby: "3.0"
          - gemfile: Gemfile
            ruby: 2.7
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - if: ${{ contains(matrix.gemfile, 'gsl') }}
        run: sudo apt-get install libgsl-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
